<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.17.3" />
    <PackageReference Include="Crc32.NET" Version="1.2.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="csDBPF">
      <HintPath>..\..\csDBPF\csDBPF\csDBPF\bin\Debug\net8.0\csDBPF.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
