<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="csDBPF">
      <HintPath>..\..\csDBPF\csDBPF\csDBPF\bin\Debug\net7.0\csDBPF.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
