<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Data\Catalog.db" />
    <None Remove="Data\PluginPacks.db" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\Catalog.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Data\PluginPacks.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="csDBPF">
      <HintPath>..\csDBPF\csDBPF\csDBPF\bin\Release\net7.0\csDBPF.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
